Draft of Battle Implementation
Can be put where we want in the hierarchy later I imagine, I can't launch it as Im having an error from Netbeans that I cant solve: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project AutoBattler: Fatal error compiling:
error: invalid target release: 17 ->
[Help 1].
Not sure what's causing it tbh or how to fix it, internet was very little help so far.